const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('src/api/dashboard.html','utf8'),recorded=JSON.parse(fs.readFileSync('tests/fixtures/predictions_runtime.json','utf8'));
class Element{constructor(){this.children=[];this.textContent='';this.value='';this.dataset={};this.classList={toggle(){}};}append(...nodes){this.children.push(...nodes);}replaceChildren(){this.children=[];this.textContent='';}setAttribute(key,value){this[key]=value;}scrollIntoView(){this.scrolled=true;}text(){return [this.textContent,...this.children.map(n=>n.text())].join(' ');}}
async function run(mode){const elements=new Map([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>[m[1],new Element()])),calls=[],clicked=[];let releaseFirst;const buttons=['all','result','goals','btts','asian_handicap','corners','cards'].map(m=>{const b=new Element();b.dataset.marketFamily=m;return b;});elements.get('min-probability').value='60';
const all=recorded.page.items.flatMap(item=>item.recommendations.map(recommendation=>({match:item.match,recommendation,as_of:item.as_of})));
const summary={total:0,settled:0,won:0,lost:0,pending:0,awaiting_data:0,void:0,success_rate:null,average_reliability:null,average_sample_size:null,last_10:[]};
const performance={summary,families:[],markets:[],items:[],total:0};
const sandbox={console,URLSearchParams,AbortSignal,AbortController,Intl,setInterval(){},setTimeout(){},clearTimeout(){},BetAppDashboard:{selectMatch:id=>clicked.push(id)},document:{getElementById:id=>elements.get(id)||null,createElement:()=>new Element(),querySelector:()=>null,querySelectorAll:selector=>selector==='[data-market-family]'?buttons:[]},fetch:async path=>{calls.push(path);let payload;if(path.startsWith('/api/predictions/best')){const q=new URLSearchParams(path.split('?')[1]),market=q.get('market');payload={items:mode==='empty'?[]:all.filter(item=>market==='all'||item.recommendation.market===market),evaluated_matches:8,generated_at:recorded.page.generated_at};if(mode==='race' && calls.filter(p=>p.startsWith('/api/predictions/best')).length===1)return await new Promise(resolve=>releaseFirst=()=>resolve({ok:true,json:async()=>payload}));}else if(path.startsWith('/api/market-performance'))payload=performance;else payload={enabled_leagues:[{id:1,name:'English Premier League'}],stats_rows:1,matches_with_corners:1,matches_with_cards:0,matches_with_referee:0,queued_backfills:0};return {ok:!(mode==='failed-board' && path.startsWith('/api/predictions/best')),json:async()=>structuredClone(payload)};}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('src/api/dashboard-market.js','utf8'),sandbox);const settle=async()=>{for(let i=0;i<10;i++)await new Promise(resolve=>setImmediate(resolve));};await settle();const api=sandbox.BetAppMarket,body=elements.get('market-picks');
if(mode==='race'){api.activate('cards');await settle();releaseFirst();await settle();assert(body.text().includes('nitelikli tahmin yok'));assert(!body.text().includes('Arsenal'));return;}
assert(elements.get('market-category-cards').children.length===5);assert(elements.get('daily-summary').children.length===7);assert(elements.get('performance-markets').text().includes('Henüz sonuçlanan'));
if(mode==='empty'){assert(body.text().includes('nitelikli tahmin yok'));return;}if(mode==='failed-board'){assert(body.text().includes('Bağlantı bekleniyor'));assert(elements.get('performance-picks').text().includes('kaydedilmiş tahmin yok'));return;}
assert(body.children.length===all.length);assert(body.text().includes('Arsenal'));assert(!body.text().includes('Kazandı'));body.children[0].onclick();assert.equal(clicked[0],all[0].match.id);body.children[0].onkeydown({key:'Enter',preventDefault(){}});assert.equal(clicked[1],clicked[0]);
elements.get('market-category-cards').children[2].onclick();await settle();assert(calls.at(-1).includes('market=')||calls.some(p=>p.includes('market=corners')));assert(body.text().includes('nitelikli tahmin yok'));assert(elements.get('predictions-section').scrolled);
elements.get('performance-market').value='cards';elements.get('performance-confidence').value='high';elements.get('performance-from').value='2026-10-01';elements.get('performance-market').onchange();await settle();assert(calls.some(p=>p.includes('/api/market-performance?') && p.includes('market=cards') && p.includes('confidence=high') && p.includes('date_from=2026-10-01')));
elements.get('fixtures-nav').onclick();assert(elements.get('matches-layout').open);}
(async()=>{for(const mode of ['populated','empty','failed-board','race'])await run(mode);console.log('market runtime: 4 scenarios passed');})().catch(error=>{console.error(error);process.exitCode=1;});
