const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('src/api/dashboard.html','utf8'),recorded=JSON.parse(fs.readFileSync('tests/fixtures/predictions_runtime.json','utf8'));
class Element{constructor(){this.children=[];this.textContent='';this.value='';this.dataset={};this.style={};this.classList={toggle(){}};}append(...nodes){this.children.push(...nodes);}replaceChildren(){this.children=[];this.textContent='';}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}focus(){}text(){return [this.textContent,...this.children.map(n=>n.text())].join(' ');}}
async function run(mode){const elements=new Map([...html.matchAll(/\bid="([^"]+)"/g)].map(m=>[m[1],new Element()])),calls=[],clicked=[];let releaseFirst;
const all=recorded.page.items.flatMap(item=>item.recommendations.map(recommendation=>({match:item.match,recommendation,as_of:item.as_of})));
const summary={total:0,settled:0,won:0,lost:0,pending:0,awaiting_data:0,void:0,success_rate:null,average_reliability:null,average_sample_size:null,last_10:[]};
const sandbox={console,URLSearchParams,AbortSignal,AbortController,Intl,setInterval(){},setTimeout(){},clearTimeout(){},location:{hash:'#home'},history:{pushState(s,t,url){sandbox.location.hash=url;},replaceState(s,t,url){sandbox.location.hash=url;}},BetAppDashboard:{selectMatch:id=>clicked.push(id),dismissDetail(){}},document:{getElementById:id=>elements.get(id)||null,createElement:()=>new Element(),querySelector:()=>null,querySelectorAll:()=>[]},fetch:async path=>{calls.push(path);let payload;
if(path.startsWith('/api/predictions/best')){const q=new URLSearchParams(path.split('?')[1]);payload={items:mode==='empty'?[]:all.filter(i=>q.get('market')==='all'||i.recommendation.market===q.get('market')),evaluated_matches:8,generated_at:recorded.page.generated_at};if(mode==='race' && !releaseFirst)return await new Promise(resolve=>releaseFirst=()=>resolve({ok:true,json:async()=>payload}));}
else if(path.startsWith('/api/predictions?'))payload={...recorded.page,items:mode==='empty'?[]:recorded.page.items};else if(path.startsWith('/api/market-performance'))payload={summary,families:[],markets:[],items:[],total:0};else if(path==='/api/leagues')payload=[];else payload={database_connected:true,enabled_leagues:[],stats_coverage_by_league:[],queued_stats_backfills:[]};return {ok:!(mode==='failed-board' && path.startsWith('/api/predictions/best')),status:503,json:async()=>structuredClone(payload)};}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('src/api/dashboard-market.js','utf8'),sandbox);const settle=async()=>{for(let i=0;i<10;i++)await new Promise(resolve=>setImmediate(resolve));};await settle();
assert(!calls.some(p=>p.startsWith('/api/market-performance')));assert(!calls.some(p=>p.includes('/statistics')));
if(mode==='populated'){const card=elements.get('prediction-cards').children[0];assert(card.text().includes('Arsenal'));card.onclick();assert.equal(clicked[0],recorded.page.items[0].match.id);}
sandbox.BetAppUI.navigate('predictions');await settle();const body=elements.get('market-picks');
if(mode==='race'){elements.get('pred-market').value='cards';await sandbox.BetAppMarket.refresh();releaseFirst();await settle();assert(!body.text().includes('Arsenal'));return;}
if(mode==='empty'){assert(body.text().includes('nitelikli tahmin yok'));return;}
if(mode==='failed-board'){assert(body.text().includes('PostgreSQL'));sandbox.BetAppUI.navigate('performance');await settle();assert(elements.get('performance-picks').text().includes('kaydedilmiş tahmin yok'));return;}
assert(body.children.length===all.length);body.children[0].onkeydown({key:'Enter',preventDefault(){}});assert.equal(clicked.at(-1),all[0].match.id);
elements.get('pred-market').value='corners';await sandbox.BetAppMarket.refresh();assert(body.text().includes('nitelikli tahmin yok'));
sandbox.BetAppUI.navigate('performance');await settle();assert.equal(elements.get('daily-summary').children.length,5);
sandbox.BetAppUI.navigate('markets');await settle();assert(elements.get('stats-league-coverage').text().includes('API'));}
(async()=>{for(const mode of ['populated','empty','failed-board','race'])await run(mode);console.log('market runtime: 4 scenarios passed');})().catch(e=>{console.error(e);process.exitCode=1;});
