/* Market terminal: only selected server recommendations and audited forward picks. */
(() => {
'use strict';
const $=id=>document.getElementById(id),node=(tag,text='',cls='')=>{const el=document.createElement(tag);el.textContent=text;el.className=cls;return el;};
const families={all:'Tümü',result:'Sonuç',double_chance:'Çifte Şans',goals:'Gol',btts:'KG',asian_handicap:'Handikap',corners:'Korner',cards:'Kart'};
const confidences={high:'Yüksek',medium:'Orta',low:'Düşük'},outcomes={won:'Kazandı',lost:'Kaybetti',pending:'Bekliyor',awaiting_data:'Final veri bekleniyor',void:'İptal / geçersiz'};
const pct=v=>v==null?'—':'%'+(100*v).toFixed(1),date=v=>v?new Date(v).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'}):'—';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const state={market:'all',league:'',date:today(),offset:0,performanceOffset:0,generation:0,performanceGeneration:0,controller:null,performanceController:null,activeLeagues:null};
const value=id=>$(id)?.value || '',write=(id,text)=>{if($(id))$(id).textContent=text;};
function cell(row,text,cls=''){row.append(node('td',text,cls));}
function availabilityMessage(availability){
 const labels={insufficient_data:'Yetersiz istatistik verisi. Korner için iki takımın korner toplamı; kart için sarı ve kırmızı toplamları gerekli.',no_upcoming_matches:'Bu tarih ve lig için yaklaşan maç yok.',filtered_out:'Nitelikli tahminler var; güven veya olasılık filtresi dışında.',no_qualified_recommendations:'Veriler değerlendirildi; kalite veya ilk üç sıralama eşiğini geçen seçim yok.'};
 const metric=availability?.markets?.[state.market];
 return (labels[availability?.status] || 'Bu filtrede nitelikli tahmin yok.')+(metric?` ${metric.model_ready_matches} / ${metric.evaluated_matches} maçın modeli hazır.`:'');
}
function renderCoverage(rows){
 const box=$('stats-league-coverage');if(!box)return;box.replaceChildren();
 for(const league of rows || []){const row=node('tr');cell(row,league.name);cell(row,String(league.finished_matches));cell(row,String(league.total_stats_rows));for(const metric of ['corners','cards']){const n=league['matches_with_'+metric],percent=league.stats_coverage_percent?.[metric];cell(row,`${n} · ${percent==null?'—':'%'+percent.toFixed(1)}`);}box.append(row);}
 if(!rows?.length)empty('stats-league-coverage','İstatistik kapsamı bekleniyor.',5);
}
function empty(id,message,span){const box=$(id);if(!box)return;box.replaceChildren();const row=node('tr'),td=node('td',message,'empty-state');td.colSpan=span;row.append(td);box.append(row);}
function openRow(row,id){row.tabIndex=0;row.dataset.matchId=String(id);row.setAttribute('aria-label','Maç analizini aç');row.onclick=()=>globalThis.BetAppDashboard?.selectMatch(id);row.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();row.onclick();}};}
async function api(path,signal){const response=await fetch(path,{signal:signal || AbortSignal.timeout(15000)});if(!response.ok)throw new Error('API unavailable');return response.json();}
function renderPicks(items){const box=$('market-picks');if(!box)return;box.replaceChildren();for(const item of items){const m=item.match,r=item.recommendation,row=node('tr');cell(row,date(m.kickoff_at));cell(row,m.league,'muted');cell(row,m.home_team+' / '+m.away_team,'match-name');cell(row,families[r.market]);cell(row,r.label);cell(row,pct(r.probability),'model-value');cell(row,pct(r.market_probability));cell(row,r.model_market_difference==null?'—':(r.model_market_difference>=0?'+':'')+(100*r.model_market_difference).toFixed(1));cell(row,confidences[r.confidence]);cell(row,String(r.sample_size));cell(row,'—');cell(row,'Bekliyor','pending');openRow(row,m.id);box.append(row);}if(!items.length)empty('market-picks','Bu filtrede nitelikli tahmin yok.',12);}
function activate(market){state.market=market;state.offset=0;document.querySelectorAll('[data-market-family]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.marketFamily===market)));refresh();}
function dailyNav(items){const box=$('daily-market-nav');if(!box)return;box.replaceChildren();for(const [market,label] of [['goals','Gol'],['corners','Korner'],['cards','Kart'],['result','Sonuç']]){const count=items.filter(item=>market==='goals'?['goals','btts'].includes(item.recommendation.market):market==='result'?['result','double_chance'].includes(item.recommendation.market):item.recommendation.market===market).length;const button=node('button',`Günün ${label} Marketleri · ${count} bu sayfada`);button.type='button';button.onclick=()=>activate(market);box.append(button);}}
async function refresh(league,dateFilter){const nextLeague=$('league-select')?value('league-select'):(league??state.league),nextDate=$('date-select')?value('date-select'):(dateFilter??state.date);if(nextLeague!==state.league || nextDate!==state.date)state.offset=0;state.league=nextLeague;state.date=nextDate;const generation=++state.generation;state.controller?.abort();state.controller=new AbortController();
const q=new URLSearchParams({limit:'20',offset:String(state.offset),market:state.market,sort:value('market-sort') || 'ranking',min_probability:String(Math.max(0,Math.min(100,Number(value('min-probability') || 0)))/100)});if(state.league)q.set('league',state.league);if(state.date)q.set('date',state.date);if(value('prediction-confidence'))q.set('confidence',value('prediction-confidence'));const search=document.querySelector('[data-team-search]')?.value;if(search)q.set('team',search);
try{const page=await api('/api/predictions/best?'+q,state.controller.signal);if(generation!==state.generation)return;renderPicks(page.items);if(!page.items.length && page.availability)empty('market-picks',availabilityMessage(page.availability),12);dailyNav(page.items);write('prediction-window',(state.date?state.date:'Önümüzdeki 7 gün')+' · '+date(page.generated_at));write('market-board-note',`${page.items.length} seçilmiş tahmin · ${page.evaluated_matches} maç değerlendirildi`);if($('market-previous'))$('market-previous').disabled=state.offset===0;if($('market-next'))$('market-next').disabled=page.items.length<20;await loadOverview(generation);}catch(error){if(generation!==state.generation)return;empty('market-picks','Bağlantı bekleniyor. Diğer paneller kullanılabilir.',12);write('market-board-note','Veri bekleniyor');if($('market-next'))$('market-next').disabled=true;}}
function renderSummary(summary){const box=$('daily-summary');if(!box)return;box.replaceChildren();const metrics=[['Toplam Tahmin',summary?.total,''],['Kazandı',summary?.won,'won'],['Kaybetti',summary?.lost,'lost'],['Bekliyor',summary?summary.pending+summary.awaiting_data:null,'pending'],['Başarı %',summary?.success_rate==null?'—':pct(summary.success_rate),''],['Ort. Güven Endeksi',summary?.average_reliability==null?'—':pct(summary.average_reliability),''],['Aktif Lig Sayısı',state.activeLeagues,'']];for(const [label,v,cls] of metrics){const card=node('div','','summary-card');card.append(node('span',label),node('b',v==null?'—':String(v),cls));box.append(card);}}
function renderCategories(data){const box=$('market-category-cards');if(!box)return;box.replaceChildren();for(const [market,label,members] of [['result','Futbol Tahminleri',['result','double_chance']],['goals','Gol Tahminleri',['goals','btts']],['corners','Korner Tahminleri',['corners']],['cards','Kart Tahminleri',['cards']],['asian_handicap','Handikap Tahminleri',['asian_handicap']]]){const source=(data?.families || []).filter(row=>members.includes(row.market));const total=key=>source.reduce((n,row)=>n+row[key],0),settled=total('settled');const card=node('button','','market-category');card.type='button';card.append(node('h3',label),node('strong',!data?'Bağlantı bekleniyor':settled?pct(total('won')/settled):'Henüz sonuç yok'),node('span',data?`${settled} sonuçlanan tahmin`:'Veri bekleniyor'));const counts=node('div','','category-counts');for(const [key,text,cls] of [['won','Kazandı','won'],['lost','Kaybetti','lost'],['pending','Bekliyor','pending']])counts.append(node('span',text+' '+(data?String(total(key)+(key==='pending'?total('awaiting_data'):0)):'—'),cls));card.append(counts,node('small','Tümünü Gör →'));card.onclick=()=>{if($('performance-market'))$('performance-market').value=market;if($('performance-exact'))$('performance-exact').value='';state.performanceOffset=0;refreshPerformance();activate(market);$('predictions-section')?.scrollIntoView({behavior:'smooth'});};box.append(card);}}
async function loadOverview(generation){const results=await Promise.allSettled([api('/api/market-performance?limit=1'),api('/api/market-performance?limit=1&date_from='+today()+'&date_to='+today()),api('/api/diagnostics')]);if(generation!==state.generation)return;document.querySelector('.connection')?.classList.toggle('connected',$('api-health')?.textContent==='Bağlı');if(results[2].status==='fulfilled'){const d=results[2].value;renderCoverage(d.stats_coverage_by_league);state.activeLeagues=d.database_connected?(d.enabled_leagues?.length ?? d.enabled_competitions):null;write('enabled-league-count',state.activeLeagues??'—');const active=d.active_backfill;write('active-backfill-progress',!d.database_connected?'Bağlantı bekleniyor':active?`${d.active_backfill_competition || 'İstatistik işi'} · ${active.processed+active.failed} / ${active.total} maç · ${active.failed} hata`:'Aktif ağır backfill işi yok.');for(const [id,key] of [['stats-count','stats_rows'],['corners-count','matches_with_corners'],['cards-count','matches_with_cards'],['referee-count','matches_with_referee'],['queued-count','queued_backfills']])write(id,d[key]??'Veri bekleniyor');const select=$('performance-league');if(select){const previous=select.value;select.replaceChildren();const all=node('option','Tüm Ligler');all.value='';select.append(all);for(const league of d.enabled_leagues || []){const option=node('option',league.name);option.value=String(league.id);select.append(option);}select.value=previous;}}
renderCategories(results[0].status==='fulfilled'?results[0].value:null);renderSummary(results[1].status==='fulfilled'?results[1].value.summary:null);}
function renderPerformance(data){const summary=data.summary;write('performance-summary',`${summary.settled} sonuçlanan · ${summary.won} kazandı · ${summary.lost} kaybetti · ${summary.pending+summary.awaiting_data} bekliyor · Başarı ${pct(summary.success_rate)} · Ortalama güven endeksi ${pct(summary.average_reliability)}`);const box=$('performance-markets');if(box){box.replaceChildren();for(const market of data.markets){const row=node('tr');cell(row,market.label);for(const key of ['settled','won','lost'])cell(row,String(market[key]),key);cell(row,String(market.pending+market.awaiting_data),'pending');cell(row,pct(market.success_rate));cell(row,pct(market.average_reliability));cell(row,market.average_sample_size==null?'—':market.average_sample_size.toFixed(1));cell(row,market.last_10.map(result=>result==='won'?'✓':result==='lost'?'×':result==='void'?'·':'…').join(' '),'mini-form');box.append(row);}if(!data.markets.length)empty('performance-markets','Henüz sonuçlanan tahmin kaydı yok. Geçmiş maçlardan tahmin üretilmez.',9);}
const picks=$('performance-picks');if(picks){picks.replaceChildren();for(const item of data.items){const row=node('tr');cell(row,date(item.captured_at));cell(row,item.match.home_team+' / '+item.match.away_team,'match-name');cell(row,item.recommendation.label);cell(row,pct(item.recommendation.probability),'model-value');cell(row,item.actual==null?'—':String(item.actual));cell(row,outcomes[item.outcome],item.outcome);openRow(row,item.match.id);picks.append(row);}if(!data.items.length)empty('performance-picks','Bu filtrede kaydedilmiş tahmin yok.',6);}
const exact=$('performance-exact');if(exact && !exact.value){exact.replaceChildren();const all=node('option','Tüm seçimler');all.value='';exact.append(all);for(const market of data.markets){const option=node('option',market.label);option.value=market.id;exact.append(option);}}
write('performance-note',`${data.total} kayıt · Sayfa ${Math.floor(state.performanceOffset/50)+1}`);if($('performance-previous'))$('performance-previous').disabled=state.performanceOffset===0;if($('performance-next'))$('performance-next').disabled=state.performanceOffset+50>=data.total;}
async function refreshPerformance(){const generation=++state.performanceGeneration;state.performanceController?.abort();state.performanceController=new AbortController();const query=new URLSearchParams({limit:'50',offset:String(state.performanceOffset),market:value('performance-market') || 'all'});for(const [id,key] of [['performance-exact','exact_market'],['performance-league','league'],['performance-from','date_from'],['performance-to','date_to'],['performance-confidence','confidence']])if(value(id))query.set(key,value(id));try{const data=await api('/api/market-performance?'+query,state.performanceController.signal);if(generation!==state.performanceGeneration)return;renderPerformance(data);}catch(error){if(generation!==state.performanceGeneration)return;write('performance-summary','Bağlantı bekleniyor');empty('performance-markets','Performans verisi bekleniyor.',9);empty('performance-picks','Bağlantı bekleniyor.',6);}}
function changed(){state.offset=0;refresh();}
document.querySelectorAll('[data-market-family]').forEach(button=>button.onclick=()=>activate(button.dataset.marketFamily));for(const id of ['prediction-confidence','min-probability','market-sort'])if($(id))$(id).onchange=changed;
for(const id of ['performance-market','performance-exact','performance-league','performance-from','performance-to','performance-confidence'])if($(id))$(id).onchange=()=>{state.performanceOffset=0;refreshPerformance();};
if($('market-previous'))$('market-previous').onclick=()=>{state.offset=Math.max(0,state.offset-20);refresh();};if($('market-next'))$('market-next').onclick=()=>{state.offset+=20;refresh();};
if($('performance-previous'))$('performance-previous').onclick=()=>{state.performanceOffset=Math.max(0,state.performanceOffset-50);refreshPerformance();};if($('performance-next'))$('performance-next').onclick=()=>{state.performanceOffset+=50;refreshPerformance();};
if($('today-board'))$('today-board').onclick=()=>{if($('date-select'))$('date-select').value=today();changed();globalThis.BetAppDashboard?.refreshMatches?.();};if($('upcoming-board'))$('upcoming-board').onclick=()=>{if($('date-select'))$('date-select').value='';changed();globalThis.BetAppDashboard?.refreshMatches?.();};
if($('fixtures-nav'))$('fixtures-nav').onclick=()=>{if($('matches-layout'))$('matches-layout').open=true;};
let timer;document.querySelectorAll('[data-team-search]').forEach(input=>input.addEventListener?.('input',()=>{clearTimeout(timer);timer=setTimeout(changed,350);}));
globalThis.BetAppMarket=Object.freeze({refresh,refreshPerformance,activate});if($('date-select'))$('date-select').value=today();renderSummary(null);renderCategories(null);refresh();refreshPerformance();setInterval(()=>{refresh();refreshPerformance();document.querySelector('.connection')?.classList.toggle('connected',$('api-health')?.textContent==='Bağlı');},30000);
})();
