/* Arctic White: API presentation, URL history and lazy loading. No model calculations. */
(() => {
'use strict';
const $=id=>document.getElementById(id),value=id=>$(id)?.value || '';
const node=(tag,text='',cls='')=>{const el=document.createElement(tag);el.textContent=text;el.className=cls;return el;};
const write=(id,text)=>{if($(id))$(id).textContent=text;},pct=v=>v==null?'—':'%'+(100*v).toFixed(1);
const date=v=>v?new Date(v).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul',dateStyle:'medium',timeStyle:'short'}):'Veri bekleniyor';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const families={all:'Tümü',result:'Sonuç',double_chance:'Çifte Şans',goals:'Gol',btts:'KG',asian_handicap:'Handikap',corners:'Korner',cards:'Sarı + Kırmızı',yellow_cards:'Sarı Kart',red_cards:'Kırmızı Kart'};
const confidences={high:'Yüksek',medium:'Orta',low:'Düşük'},outcomes={won:'Kazandı',lost:'Kaybetti',pending:'Bekliyor',awaiting_data:'Final veri bekleniyor',void:'İptal / geçersiz'};
const pages=['home','predictions','markets','matches','performance'];
const state={page:'home',market:'goals',offset:0,performanceOffset:0,controllers:new Map(),lastMatch:null};
function cell(row,text,cls=''){const el=node('td',text,cls);row.append(el);return el;}
function empty(id,text,span,retryFn){const box=$(id);if(!box)return;box.replaceChildren();if(span){const row=node('tr'),td=cell(row,'','empty-state');td.colSpan=span;td.append(node('span',text));if(retryFn){const btn=node('button','Yeniden Dene','retry-action');btn.type='button';btn.onclick=()=>retryFn();td.append(btn);}box.append(row);}else{const wrap=node('div','','empty-state');wrap.append(node('p',text));if(retryFn){const btn=node('button','Yeniden Dene','retry-action');btn.type='button';btn.onclick=()=>retryFn();wrap.append(btn);}box.append(wrap);}box.setAttribute('aria-busy','false');}
function loading(id,span){const box=$(id);if(!box)return;if(!box.children.length || box.dataset?.loaded!=='true')empty(id,'API verileri yükleniyor…',span);box.setAttribute('aria-busy','true');}
function done(id){const box=$(id);if(box){box.setAttribute('aria-busy','false');box.dataset.loaded='true';}}
function errorText(e){if(e.name==='TimeoutError' || e.status===504)return 'API isteği zaman aşımına uğradı. Yeniden deneyin.';return e.status===503?'PostgreSQL verileri şu anda kullanılamıyor. Yeniden bağlantı bekleniyor.':'API kullanılamıyor. Bağlantı bekleniyor; diğer bölümleri kullanabilirsiniz.';}
async function api(path,signal){const r=await fetch(path,{signal:signal || AbortSignal.timeout(15000)});if(!r.ok){const e=new Error('API unavailable');e.status=r.status;throw e;}return r.json();}
async function request(key,path,success,failure){const pending=state.controllers.get(key);if(pending && !pending.signal.aborted && pending.path===path)return;pending?.abort();const c=new AbortController();c.path=path;state.controllers.set(key,c);try{const data=await api(path,AbortSignal.any([c.signal,AbortSignal.timeout(15000)]));if(!c.signal.aborted)success(data);}catch(e){if(!c.signal.aborted)failure?.(e);}finally{if(state.controllers.get(key)===c)state.controllers.delete(key);}}
function openRow(row,id){row.dataset.matchId=String(id);row.tabIndex=0;row.setAttribute('aria-label','Maç analizini aç');row.onclick=()=>globalThis.BetAppDashboard?.selectMatch(id);row.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();row.onclick();}};}
function availabilityMessage(a){return ({insufficient_data:'Yetersiz istatistiksel geçmiş. Tam korner veya sarı + kırmızı kart kayıtları bekleniyor.',no_upcoming_matches:'Bu tarih ve lig için yaklaşan maç yok.',filtered_out:'Nitelikli tahminler var; güven veya olasılık filtresi dışında.',no_qualified_recommendations:'Modelin kalite ve sıralama eşiklerini geçen tahmin yok.'})[a?.status] || 'Bu filtrede modelin seçtiği nitelikli tahmin yok.';}
function card(item){const m=item.match,recs=(item.recommendations || []).slice(0,3);if(!recs.length)return null;const el=node('article','','prediction-card');el.setAttribute('role','button');el.setAttribute('aria-label',`${m.home_team} — ${m.away_team}, analizi aç`);el.tabIndex=0;el.dataset.matchId=String(m.id);
 const meta=node('div','','card-meta');meta.append(node('span',m.league,'league-label'),node('time',date(m.kickoff_at)));el.append(meta);const teams=node('h3','','card-teams');teams.append(node('span',m.home_team),node('span',m.away_team));el.append(teams);
 const primary=node('div','','pick-primary');primary.append(node('span','EN GÜÇLÜ TAHMİN','eyebrow'));const line=node('div','','pick-line');line.append(node('span',recs[0].label),node('strong',pct(recs[0].probability)));primary.append(line);const metaPick=node('div','','pick-meta');metaPick.append(node('span',`${recs[0].sample_size} maç örneği`),node('span',`${confidences[recs[0].confidence]} güven`,'confidence-badge'));primary.append(metaPick);el.append(primary);
 for(const r of recs.slice(1)){const row=node('div','','other-pick');row.append(node('span',r.label),node('b',`${pct(r.probability)} · ${confidences[r.confidence]}`));el.append(row);}const footer=node('div','','card-footer');footer.append(node('span',`${recs.length} nitelikli seçim`),node('span','Analizi Aç →','prediction-open'));el.append(footer);el.onclick=()=>globalThis.BetAppDashboard?.selectMatch(m.id);el.onkeydown=e=>{if(e.target===el && ['Enter',' '].includes(e.key)){e.preventDefault();el.onclick();}};return el;
}
function renderCards(id,items,message){const box=$(id);if(!box)return;box.replaceChildren();for(const item of items){const el=card(item);if(el)box.append(el);}if(!box.children.length)empty(id,message || 'Modelin kalite eşiklerini geçen yaklaşan maç tahmini bulunmuyor.');done(id);}
function groupPicks(items){const grouped=new Map();for(const item of items){if(!grouped.has(item.match.id))grouped.set(item.match.id,{match:item.match,recommendations:[]});grouped.get(item.match.id).recommendations.push(item.recommendation);}return [...grouped.values()];}
async function home(){loading('prediction-cards');return request('home','/api/predictions?limit=6',p=>{renderCards('prediction-cards',p.items,availabilityMessage(p.availability));const cache=p.cache||{};const staleText=cache.stale?' · Önceden hesaplanmış (güncelleme bekleniyor)':'';write('home-prediction-note',`Önümüzdeki ${p.window_hours===72?'72 saat':'7 gün'} · ${date(p.generated_at)}${staleText}`);},e=>empty('prediction-cards',errorText(e),null,()=>home()));}
function renderPicks(items){const box=$('market-picks');if(!box)return;box.replaceChildren();for(const item of items){const m=item.match,r=item.recommendation,row=node('tr'),fixture=cell(row,'');fixture.append(node('strong',`${m.home_team} — ${m.away_team}`),node('small',`${m.league} · ${date(m.kickoff_at)}`));const market=cell(row,'');market.append(node('strong',r.label),node('small',families[r.market]));cell(row,'').append(node('strong',pct(r.probability),'probability'));cell(row,confidences[r.confidence]);const q=r.evidence || {};cell(row,`${r.sample_size} maç · Güven endeksi ${pct(r.reliability)}${q.home_sample!=null?` · Takım örneği ${q.home_sample}/${q.away_sample}`:''}`);openRow(row,m.id);box.append(row);}done('market-picks');}
async function refresh(){if(state.page!=='predictions')return;loading('market-picks',5);const q=new URLSearchParams({limit:'20',offset:String(state.offset),market:value('pred-market') || 'all',sort:value('market-sort') || 'ranking',min_probability:String(Math.max(0,Math.min(100,Number(value('min-probability') || 0)))/100)});for(const [id,key] of [['pred-date','date'],['pred-league','league'],['prediction-confidence','confidence'],['pred-team','team']])if(value(id))q.set(key,value(id));return request('picks','/api/predictions/best?'+q,p=>{renderPicks(p.items);if(!p.items.length)empty('market-picks',availabilityMessage(p.availability),5);const cache=p.cache||{};const staleText=cache.stale?' (Önceden hesaplanmış · Güncelleme kuyrukta)':'';write('prediction-window',`${date(p.generated_at)}${staleText}`);write('market-board-note',`${p.items.length} seçilmiş tahmin · ${p.evaluated_matches} maç değerlendirildi`);if($('market-previous'))$('market-previous').disabled=state.offset===0;if($('market-next'))$('market-next').disabled=p.items.length<20;},e=>{empty('market-picks',errorText(e),5,()=>refresh());write('market-board-note','Veri bekleniyor');});}

function renderCoverage(rows){const box=$('stats-league-coverage');if(!box)return;box.replaceChildren();for(const league of rows || []){const row=node('tr');const label=cell(row,league.name);if(league.stats_backfill){const j=league.stats_backfill;label.append(node('small',` · ${({queued:'Sırada',running:'İşleniyor',completed:'Tamamlandı',partial:'Kısmen tamamlandı',failed:'Yeniden deneme bekleniyor'})[j.status] || j.status}${j.total?' · '+j.processed+'/'+j.total:''}${j.failed?' · '+j.failed+' hata':''}`));}cell(row,String(league.finished_matches));cell(row,String(league.total_stats_rows));for(const metric of ['corners','cards']){const n=league['matches_with_'+metric],percent=league.stats_coverage_percent?.[metric],td=cell(row,`${n} / ${league.finished_matches} · ${percent==null?'—':'%'+percent.toFixed(1)}`),meter=node('div','','coverage-meter'),bar=node('span');bar.style.width=Math.max(0,Math.min(100,percent || 0))+'%';meter.append(bar);td.append(meter);}box.append(row);}if(!rows?.length)empty('stats-league-coverage','Lig bazında kapsam verisi henüz API tarafından sağlanmıyor.',5);}
async function diagnostics(){return request('diagnostics','/api/diagnostics',d=>{renderCoverage(d.stats_coverage_by_league);write('enabled-league-count',d.database_connected?(d.enabled_leagues?.length ?? d.enabled_competitions ?? '—'):'—');const active=d.active_stats_backfill || d.active_backfill;write('active-backfill-progress',!d.database_connected?'PostgreSQL kullanılamıyor':active?`Backfill çalışıyor · ${active.league || d.active_backfill_competition || 'İstatistik'} · ${active.processed+active.failed} / ${active.total} · ${active.failed} hata`:'Aktif istatistik backfill işi yok');write('queued-count',d.queued_stats_backfills?.length ?? d.queued_backfills ?? '—');},e=>{write('active-backfill-progress',errorText(e));empty('stats-league-coverage',errorText(e),5);});}
function metrics(id,entries){const box=$(id);if(!box)return;box.replaceChildren();for(const [label,text,cls] of entries){const el=node('div','','summary-card');el.append(node('span',label),node('b',String(text??'—'),cls || ''));box.append(el);}}
async function marketAnalysis(){if(state.page!=='markets')return;const market=state.market;loading('market-analysis-picks');diagnostics();request('market-picks',`/api/predictions/best?limit=100&market=${market}&date=${today()}`,p=>{renderCards('market-analysis-picks',groupPicks(p.items),availabilityMessage(p.availability));const samples=p.items.map(i=>i.recommendation.sample_size);write('market-analysis-note',samples.length?`Örneklem: ${Math.min(...samples)}–${Math.max(...samples)} maç`:`${p.evaluated_matches} maç değerlendirildi`);},e=>empty('market-analysis-picks',errorText(e)));request('market-performance',`/api/market-performance?limit=1&market=${market}`,d=>{const s=d.summary;metrics('market-category-cards',[['Kaydedilmiş tahmin',s.total],['Sonuçlanan',s.settled],['Gerçek başarı oranı',pct(s.success_rate)]]);},e=>empty('market-category-cards',errorText(e)));}
function activate(market){state.market=market;document.querySelectorAll('[data-market-family]').forEach(b=>{const selected=b.dataset.marketFamily===market;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});$('market-analysis-panel')?.setAttribute('aria-labelledby','market-tab-'+market);marketAnalysis();}
function renderPerformance(data){const summary=data.summary;write('performance-summary',`${summary.settled} sonuçlanan · ${summary.won} kazandı · ${summary.lost} kaybetti · ${summary.pending+summary.awaiting_data} bekliyor · Başarı ${pct(summary.success_rate)} · Ortalama güven endeksi ${pct(summary.average_reliability)}`);const box=$('performance-markets');if(box){box.replaceChildren();for(const market of data.markets){const row=node('tr');cell(row,market.label);for(const key of ['settled','won','lost'])cell(row,String(market[key]),key);cell(row,String(market.pending+market.awaiting_data),'pending');cell(row,pct(market.success_rate));cell(row,pct(market.average_reliability));cell(row,market.average_sample_size==null?'—':market.average_sample_size.toFixed(1));cell(row,market.last_10.map(result=>result==='won'?'✓':result==='lost'?'×':result==='void'?'·':'…').join(' '),'mini-form');box.append(row);}if(!data.markets.length)empty('performance-markets','Henüz sonuçlanan tahmin kaydı yok. Geçmiş maçlardan tahmin üretilmez.',9);}
const picks=$('performance-picks');if(picks){picks.replaceChildren();for(const item of data.items){const row=node('tr');cell(row,date(item.captured_at));cell(row,item.match.home_team+' / '+item.match.away_team,'match-name');cell(row,item.recommendation.label);cell(row,pct(item.recommendation.probability),'model-value');cell(row,item.actual==null?'—':String(item.actual));cell(row,outcomes[item.outcome],item.outcome);openRow(row,item.match.id);picks.append(row);}if(!data.items.length)empty('performance-picks','Bu filtrede kaydedilmiş tahmin yok.',6);}
const exact=$('performance-exact');if(exact && !exact.value){exact.replaceChildren();const all=node('option','Tüm seçimler');all.value='';exact.append(all);for(const market of data.markets){const option=node('option',market.label);option.value=market.id;exact.append(option);}}
write('performance-note',`${data.total} kayıt · Sayfa ${Math.floor(state.performanceOffset/50)+1}`);if($('performance-previous'))$('performance-previous').disabled=state.performanceOffset===0;if($('performance-next'))$('performance-next').disabled=state.performanceOffset+50>=data.total;}

async function refreshPerformance(){if(state.page!=='performance')return;const q=new URLSearchParams({limit:'50',offset:String(state.performanceOffset),market:value('performance-market') || 'all'});for(const [id,key] of [['performance-exact','exact_market'],['performance-league','league'],['performance-from','date_from'],['performance-to','date_to'],['performance-confidence','confidence']])if(value(id))q.set(key,value(id));loading('performance-picks',6);write('performance-summary','API verileri yükleniyor…');return request('performance','/api/market-performance?'+q,d=>{renderPerformance(d);const s=d.summary;metrics('daily-summary',[['Toplam',s.total],['Kazandı',s.won,'won'],['Kaybetti',s.lost,'lost'],['Bekliyor',s.pending+s.awaiting_data,'pending'],['Başarı oranı',pct(s.success_rate)]]);done('performance-picks');},e=>{write('performance-summary',e.status===400?'Tarih aralığını kontrol edin.':errorText(e));empty('performance-picks',errorText(e),6);empty('performance-markets','Performans verisi bekleniyor.',9);});}
async function leagues(){return request('leagues','/api/leagues',rows=>{write('enabled-league-count',String(rows.length));document.querySelectorAll('[data-league-options]').forEach(select=>{const before=select.value;select.replaceChildren();const all=node('option','Tüm Ligler');all.value='';select.append(all);for(const league of rows){const option=node('option',league.name);option.value=String(league.id);select.append(option);}select.value=before;});},()=>{});}
function parseRoute(){const hash=(globalThis.location?.hash || '#home').slice(1);if(/^match=\d+$/.test(hash))return {page:'home',match:Number(hash.slice(6))};const [section,search='']=hash.split('?');return {page:pages.includes(section)?section:'home',match:Number(new URLSearchParams(search).get('match')) || null};}
function loadPage(){if(document.hidden)return;if(state.page==='home')home();else if(state.page==='predictions')refresh();else if(state.page==='markets')marketAnalysis();else if(state.page==='performance')refreshPerformance();else globalThis.BetAppDashboard?.refreshMatches();}
function restore(){const r=parseRoute(),changed=state.page!==r.page;state.page=r.page;if(changed)for(const [key,c] of state.controllers)if(key!=='leagues')c.abort();document.querySelectorAll('[data-page]').forEach(s=>s.hidden=s.dataset.page!==state.page);document.querySelectorAll('[data-page-link]').forEach(link=>{if(link.dataset.pageLink===state.page)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});if(changed || !state.loaded){state.loaded=true;loadPage();if(changed)document.querySelector(`[data-page="${state.page}"] h1`)?.focus({preventScroll:true});}if(r.match){if(state.lastMatch!==r.match && globalThis.BetAppDashboard){state.lastMatch=r.match;globalThis.BetAppDashboard.selectMatch(r.match,false,false,true);}}else{state.lastMatch=null;globalThis.BetAppDashboard?.dismissDetail?.();}}
function openMatch(id){state.lastMatch=id;globalThis.history?.pushState({betMatch:id},'',`#${state.page}?match=${id}`);}
function closeMatch(){state.lastMatch=null;if(globalThis.history?.state?.betMatch)globalThis.history.back();else{globalThis.history?.replaceState(null,'',`#${state.page}`);restore();}}
function navigate(page){if(!pages.includes(page))return;globalThis.history?.pushState(null,'',`#${page}`);restore();}
function tabs(selector,action){document.querySelectorAll(selector).forEach(b=>{b.onclick=()=>action(b);b.onkeydown=e=>{const items=[...document.querySelectorAll(selector)],i=items.indexOf(b);let next;if(e.key==='ArrowRight')next=(i+1)%items.length;else if(e.key==='ArrowLeft')next=(i+items.length-1)%items.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=items.length-1;else return;e.preventDefault();items[next].focus();action(items[next]);};});}
globalThis.BetAppUI=Object.freeze({active:p=>state.page===p,openMatch,closeMatch,restore,navigate,refresh:()=>{leagues();loadPage();},isArctic:true});
globalThis.BetAppMarket=Object.freeze({refresh,refreshPerformance,activate});
document.querySelectorAll('[data-page-link],.brand,.primary-button,.text-link,.coverage-link').forEach(link=>link.onclick=e=>{e.preventDefault();navigate(link.getAttribute('href').slice(1));});
globalThis.addEventListener?.('popstate',restore);globalThis.addEventListener?.('hashchange',restore);
const changed=()=>{state.offset=0;refresh();};for(const id of ['pred-date','pred-league','pred-market','prediction-confidence','min-probability','market-sort'])if($(id))$(id).onchange=changed;
let searchTimer;if($('pred-team'))$('pred-team').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(changed,300);};if($('global-search'))$('global-search').oninput=()=>{if($('pred-team'))$('pred-team').value=value('global-search');clearTimeout(searchTimer);searchTimer=setTimeout(()=>{navigate('predictions');changed();},300);};
tabs('[data-market-family]',b=>activate(b.dataset.marketFamily));
for(const id of ['performance-market','performance-exact','performance-league','performance-from','performance-to','performance-confidence'])if($(id))$(id).onchange=()=>{state.performanceOffset=0;refreshPerformance();};
if($('market-previous'))$('market-previous').onclick=()=>{state.offset=Math.max(0,state.offset-20);refresh();};if($('market-next'))$('market-next').onclick=()=>{state.offset+=20;refresh();};if($('performance-previous'))$('performance-previous').onclick=()=>{state.performanceOffset=Math.max(0,state.performanceOffset-50);refreshPerformance();};if($('performance-next'))$('performance-next').onclick=()=>{state.performanceOffset+=50;refreshPerformance();};if($('today-board'))$('today-board').onclick=()=>{$('pred-date').value=today();changed();};if($('upcoming-board'))$('upcoming-board').onclick=()=>{$('pred-date').value='';changed();};
if($('search-toggle'))$('search-toggle').onclick=()=>{const open=$('global-search-label').classList.toggle('search-open');$('search-toggle').setAttribute('aria-expanded',String(open));if(open)$('global-search').focus();};
leagues();restore();setInterval(loadPage,30000);
})();
